FROM node:current-alpine AS development
ENV NODE_ENV development
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY ./package.json .
# Install latest npm/pnpm
RUN npm i -g pnpm
# Install package
# RUN npm install --verbose
RUN pnpm install
# Copy app files
COPY . .
# Expose port
EXPOSE 3000
# Start the app
CMD ["pnpm", "start:host"]